name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
            ecosystem.config.js
            school_district_data
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build-files

      - name: List downloaded artifact
        run: ls -la build-files

      - name: Ensure target directory exists on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/us-school-districts-api

      - name: Copy Build Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build-files/.'
          target: '/root/us-school-districts-api/'
          strip_components: 1

      - name: List deployment directory contents
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'ls -la /root/us-school-districts-api/'

      - name: Install Node Modules and Setup Database on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/us-school-districts-api
            npm ci
            # Rebuild better-sqlite3 for current Node version
            npm rebuild better-sqlite3 || npm install better-sqlite3

            # Ensure school_district_data directory exists
            mkdir -p school_district_data

            # Check if shapefile exists and is complete
            SHAPEFILE_OK=false
            if [ -f "school_district_data/EDGE_SCHOOLDISTRICT_TL24_SY2324.shp" ]; then
              SHP_SIZE=$(stat -c%s school_district_data/EDGE_SCHOOLDISTRICT_TL24_SY2324.shp 2>/dev/null || echo "0")
              SHP_SIZE_MB=$((SHP_SIZE / 1024 / 1024))
              if [ $SHP_SIZE_MB -ge 200 ]; then
                echo "✅ Shapefile exists and appears complete (${SHP_SIZE_MB}MB)"
                SHAPEFILE_OK=true
              else
                echo "⚠️ Shapefile exists but is incomplete (${SHP_SIZE_MB}MB, expected ~298MB)"
                echo "Removing incomplete shapefile..."
                rm -f school_district_data/EDGE_SCHOOLDISTRICT_TL24_SY2324.*
              fi
            fi

            # Download shapefile if not present or incomplete
            if [ "$SHAPEFILE_OK" = false ]; then
              echo "Downloading NCES shapefile (complete dataset with 13,382 districts)..."
              cd school_district_data
              # Download the COMPLETE shapefile from NCES (not the simplified Census TIGER version!)
              wget -q --show-progress "https://nces.ed.gov/programs/edge/data/EDGE_SCHOOLDISTRICT_TL24_SY2324.zip" -O EDGE_SCHOOLDISTRICT_TL24_SY2324.zip
              if [ $? -eq 0 ]; then
                unzip -q -o EDGE_SCHOOLDISTRICT_TL24_SY2324.zip
                rm -f EDGE_SCHOOLDISTRICT_TL24_SY2324.zip
                echo "✅ NCES shapefile downloaded successfully"
                # Verify it's complete
                SHP_SIZE=$(stat -c%s EDGE_SCHOOLDISTRICT_TL24_SY2324.shp 2>/dev/null || echo "0")
                SHP_SIZE_MB=$((SHP_SIZE / 1024 / 1024))
                echo "Shapefile size: ${SHP_SIZE_MB}MB (expected ~298MB)"
              else
                echo "ERROR: Could not download shapefile from NCES"
                echo "Please manually download from: https://nces.ed.gov/programs/edge/Geographic/DistrictBoundaries"
                exit 1
              fi
              cd ..
            fi

            # Ensure database exists
            if [ ! -f "school_district_data/districts.db" ]; then
              echo "Database not found, creating from shapefile..."
              npm run setup-db
            fi

            # Verify database exists and is valid
            if [ -f "school_district_data/districts.db" ]; then
              DB_SIZE=$(stat -c%s "school_district_data/districts.db" 2>/dev/null)
              if [ -n "$DB_SIZE" ] && [ "$DB_SIZE" -gt 100000000 ]; then
                echo "Database verified ($(($DB_SIZE / 1024 / 1024))MB)"
              else
                echo "Database seems invalid, recreating..."
                rm -f school_district_data/districts.db
                npm run setup-db
              fi
            else
              echo "Failed to create database!"
              exit 1
            fi

      - name: Start or Reload and Save PM2 Process on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/us-school-districts-api
            pm2 startOrReload ecosystem.config.js
            pm2 save
